/*============================================================================
 * cmd_args.cpp - CLI argument parser
 *============================================================================*/

#include "cmd_args.hpp"
#include "backend_interface.hpp"
#include "log.hpp"
#include <cctype>
#include <cstdio>
#include <cstdlib>
#include <cstring>

void print_usage(const char *prog)
{
    printf("Unified Benchmark Tool - Multi-framework inference benchmark\n\n");
    printf("Usage: %s <model_path> [options]\n\n", prog);
    printf("Options:\n");
    printf("  --model <path>      Model file path\n");
    printf("  --input <path>      Input data file (binary float32)\n");
    printf("  --input-list <path> Text file listing input .bin files (one per line,\n");
    printf("                      or space-separated). Paths relative to the list file.\n");
    printf("                      Generated by tools/generate_test_data_for_onnx.py.\n");
    printf("  --input-format <fmt> Input data format: auto|float32|uint8 (default: auto)\n");
    printf("  --repeat <N>        Benchmark repeat count (default: 100)\n");
    printf("  --warmup <N>        Warmup runs (default: 1)\n");
    printf("  --threads <N>       Number of threads (default: 4)\n");
    printf("  --output-dir <dir>  Output directory for saved outputs\n");
    printf("  --csv <path>        CSV output path (default: summary.csv)\n");
    printf("  --save-input        Save generated input to file\n");
    printf("  --no-save-output    Don't save output tensors\n");
    printf("  --no-csv            Don't write CSV\n");
    printf("  --no-output-print   Don't print output summary\n");
    printf("  --backend <list>    Comma-separated backend names to RUN (default: all)\n");
    printf("                      Examples: --backend ONNX_CPU,MNN_OpenCL_FP16\n");
    printf("  --no-backend <list> Comma-separated backend names to EXCLUDE\n");
    printf("                      Examples: --no-backend ONNX_OpenVINO_GPU,ONNX_DML_NPU\n");
    printf("  --log-level <N|name> Log level: 0/off, 1/debug, 2/info, 3/warn, 4/error\n");
    printf("                      (default: info)\n");
    printf("  --help              Show this help\n");
    printf("  --version           Show version\n");
}

bool parse_cmd_args(int argc, char *argv[], BenchConfig &cfg)
{
    bool has_backend_filter = false;
    for (int i = 1; i < argc; ++i) {
        if (strcmp(argv[i], "--help") == 0 || strcmp(argv[i], "-h") == 0) {
            print_usage(argv[0]);
            return false;
        }
        if (strcmp(argv[i], "--version") == 0) {
            printf("Unified Benchmark Tool v2.0 (C++)\n");
            return false;
        }
        if (strcmp(argv[i], "--model") == 0 && i + 1 < argc) {
            cfg.model_path = argv[++i];
        } else if (strcmp(argv[i], "--input") == 0 && i + 1 < argc) {
            cfg.input_path = argv[++i];
        } else if (strcmp(argv[i], "--input-list") == 0 && i + 1 < argc) {
            cfg.input_list_path = argv[++i];
        } else if (strcmp(argv[i], "--input-format") == 0 && i + 1 < argc) {
            const char *f = argv[++i];
            if (stricmp_(f, "float32") == 0 || stricmp_(f, "fp32") == 0) {
                cfg.input_format = InputDataFormat::Float32;
            } else if (stricmp_(f, "uint8") == 0 || stricmp_(f, "u8") == 0) {
                cfg.input_format = InputDataFormat::UInt8;
            } else if (stricmp_(f, "auto") == 0) {
                cfg.input_format = InputDataFormat::Auto;
            } else {
                LOGW("Unknown --input-format '%s', using auto", f);
                cfg.input_format = InputDataFormat::Auto;
            }
        } else if (strcmp(argv[i], "--repeat") == 0 && i + 1 < argc) {
            cfg.repeat = atoi(argv[++i]);
            if (cfg.repeat < 1) {
                cfg.repeat = 1;
            }
        } else if (strcmp(argv[i], "--warmup") == 0 && i + 1 < argc) {
            cfg.warmup_runs = atoi(argv[++i]);
            if (cfg.warmup_runs < 0) {
                cfg.warmup_runs = 0;
            }
        } else if (strcmp(argv[i], "--threads") == 0 && i + 1 < argc) {
            cfg.num_threads = atoi(argv[++i]);
            if (cfg.num_threads < 1) {
                cfg.num_threads = 1;
            }
        } else if (strcmp(argv[i], "--output-dir") == 0 && i + 1 < argc) {
            cfg.output_dir = argv[++i];
        } else if (strcmp(argv[i], "--csv") == 0 && i + 1 < argc) {
            cfg.csv_path = argv[++i];
        } else if (strcmp(argv[i], "--save-input") == 0) {
            cfg.save_input = true;
        } else if (strcmp(argv[i], "--no-save-output") == 0) {
            cfg.save_output = false;
        } else if (strcmp(argv[i], "--no-csv") == 0) {
            cfg.enable_csv = false;
        } else if (strcmp(argv[i], "--no-output-print") == 0) {
            cfg.enable_output = false;
        } else if (strcmp(argv[i], "--log-level") == 0 && i + 1 < argc) {
            const char *lv = argv[++i];
            /* Accept numeric level or a string name */
            if (isdigit((unsigned char)lv[0])) {
                cfg.log_level = atoi(lv);
            } else if (stricmp_(lv, "off") == 0) {
                cfg.log_level = 0;
            } else if (stricmp_(lv, "debug") == 0 || stricmp_(lv, "dbg") == 0) {
                cfg.log_level = 1;
            } else if (stricmp_(lv, "info") == 0) {
                cfg.log_level = 2;
            } else if (stricmp_(lv, "warn") == 0 || stricmp_(lv, "warning") == 0) {
                cfg.log_level = 3;
            } else if (stricmp_(lv, "error") == 0 || stricmp_(lv, "err") == 0) {
                cfg.log_level = 4;
            } else {
                LOGW("Unknown --log-level '%s', using info", lv);
                cfg.log_level = 2;
            }
            if (cfg.log_level < 0) {
                cfg.log_level = 0;
            }
            if (cfg.log_level > 4) {
                cfg.log_level = 4;
            }
        } else if (strcmp(argv[i], "--backend") == 0 && i + 1 < argc) {
            has_backend_filter = true;
            const char *list = argv[++i];
            const char *p = list;
            while (*p) {
                /* Skip leading spaces */
                while (*p == ' ') {
                    ++p;
                }
                if (!*p) {
                    break;
                }
                /* Find end of this token (comma or end) */
                const char *end = p;
                while (*end && *end != ',') {
                    ++end;
                }
                /* Extract token */
                std::string token(p, end - p);
                if (!token.empty()) {
                    int found = BackendRegistry::FindByName(token.c_str());
                    if (found >= 0) {
                        cfg.backend_ids.push_back(found);
                    } else {
                        LOGW("Unknown backend name: %s", token.c_str());
                    }
                }
                p = (*end == ',') ? end + 1 : end;
            }
        } else if (strcmp(argv[i], "--no-backend") == 0 && i + 1 < argc) {
            const char *list = argv[++i];
            const char *p = list;
            while (*p) {
                /* Skip leading spaces */
                while (*p == ' ') {
                    ++p;
                }
                if (!*p) {
                    break;
                }
                /* Find end of this token (comma or end) */
                const char *end = p;
                while (*end && *end != ',') {
                    ++end;
                }
                /* Extract token */
                std::string token(p, end - p);
                if (!token.empty()) {
                    int found = BackendRegistry::FindByName(token.c_str());
                    if (found >= 0) {
                        cfg.no_backend_ids.push_back(found);
                    } else {
                        LOGW("Unknown backend name: %s", token.c_str());
                    }
                }
                p = (*end == ',') ? end + 1 : end;
            }
        } else if (argv[i][0] != '-') {
            /* Positional argument = model path */
            if (cfg.model_path.empty()) {
                cfg.model_path = argv[i];
            } else {
                LOGW("Ignoring extra positional argument: %s", argv[i]);
            }
        } else {
            LOGW("Unknown option: %s", argv[i]);
        }
    }

    if (cfg.model_path.empty()) {
        LOGE("No model path specified. Use --model <path> or positional arg.");
        print_usage(argv[0]);
        return false;
    }

    if (has_backend_filter && cfg.backend_ids.empty()) {
        LOGE("--backend specified but no valid backend names found");
        return false;
    }

    return true;
}
